project_id = "cxcfxnbvtddwebqprile"

[functions.property-ai-assistant]
verify_jwt = false

[functions.send-analysis]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false