project_id = "cxcfxnbvtddwebqprile"

[functions.property-ai-assistant]
verify_jwt = false

[functions.send-analysis]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.property-data-analysis]
verify_jwt = false

[functions.web-data-scraper]
verify_jwt = false

[functions.signnow-integration]
verify_jwt = false

[functions.equifax-credit-check]
verify_jwt = false

[functions.property-data-extractor]
verify_jwt = true

[functions.admin-auth-fix]
verify_jwt = true

[functions.admin-user-management]
verify_jwt = true

[functions.admin-operations]
verify_jwt = true

[functions.generate-report-data]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = false

[functions.generate-valuation-rationale]
verify_jwt = false

[functions.generate-isfv-report]
verify_jwt = false

[functions.domain-integration]
verify_jwt = true
