-- Add comprehensive fields to sales_evidence table
ALTER TABLE public.sales_evidence 
ADD COLUMN IF NOT EXISTS unit_number text,
ADD COLUMN IF NOT EXISTS street_number text,
ADD COLUMN IF NOT EXISTS street_name text,
ADD COLUMN IF NOT EXISTS street_type text,
ADD COLUMN IF NOT EXISTS suburb text,
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS postcode text,
ADD COLUMN IF NOT EXISTS lot_number text,
ADD COLUMN IF NOT EXISTS plan_number text,
ADD COLUMN IF NOT EXISTS plan_type text,
ADD COLUMN IF NOT EXISTS local_government_area text,
ADD COLUMN IF NOT EXISTS ward text,
ADD COLUMN IF NOT EXISTS parish text,
ADD COLUMN IF NOT EXISTS county text,
ADD COLUMN IF NOT EXISTS title_particulars text,
ADD COLUMN IF NOT EXISTS zoning text,
ADD COLUMN IF NOT EXISTS property_description text,
ADD COLUMN IF NOT EXISTS building_type text,
ADD COLUMN IF NOT EXISTS construction_type text,
ADD COLUMN IF NOT EXISTS roof_type text,
ADD COLUMN IF NOT EXISTS external_walls text,
ADD COLUMN IF NOT EXISTS year_built integer,
ADD COLUMN IF NOT EXISTS year_renovated integer,
ADD COLUMN IF NOT EXISTS condition_rating text,
ADD COLUMN IF NOT EXISTS quality_rating text,
ADD COLUMN IF NOT EXISTS view_rating text,
ADD COLUMN IF NOT EXISTS aspect text,
ADD COLUMN IF NOT EXISTS topography text,
ADD COLUMN IF NOT EXISTS soil_type text,
ADD COLUMN IF NOT EXISTS services text,
ADD COLUMN IF NOT EXISTS easements text,
ADD COLUMN IF NOT EXISTS encumbrances text,
ADD COLUMN IF NOT EXISTS heritage_listing boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS flooding_risk text,
ADD COLUMN IF NOT EXISTS bushfire_risk text,
ADD COLUMN IF NOT EXISTS coastal_erosion_risk text,
ADD COLUMN IF NOT EXISTS contamination_risk text,
ADD COLUMN IF NOT EXISTS is_strata boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS strata_scheme_number text,
ADD COLUMN IF NOT EXISTS strata_lot_number text,
ADD COLUMN IF NOT EXISTS strata_plan_number text,
ADD COLUMN IF NOT EXISTS strata_manager text,
ADD COLUMN IF NOT EXISTS strata_fees_quarterly numeric,
ADD COLUMN IF NOT EXISTS strata_fees_annual numeric,
ADD COLUMN IF NOT EXISTS sinking_fund_balance numeric,
ADD COLUMN IF NOT EXISTS administrative_fund_balance numeric,
ADD COLUMN IF NOT EXISTS special_levies numeric,
ADD COLUMN IF NOT EXISTS body_corporate_name text,
ADD COLUMN IF NOT EXISTS management_rights boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS letting_rights boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS common_property_description text,
ADD COLUMN IF NOT EXISTS exclusive_use_areas text,
ADD COLUMN IF NOT EXISTS parking_type text,
ADD COLUMN IF NOT EXISTS parking_spaces integer,
ADD COLUMN IF NOT EXISTS storage_areas text,
ADD COLUMN IF NOT EXISTS balcony_area numeric,
ADD COLUMN IF NOT EXISTS courtyard_area numeric,
ADD COLUMN IF NOT EXISTS garden_area numeric,
ADD COLUMN IF NOT EXISTS pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS spa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS tennis_court boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gym boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_features text,
ADD COLUMN IF NOT EXISTS lift_access boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS wheelchair_access boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS air_conditioning text,
ADD COLUMN IF NOT EXISTS heating text,
ADD COLUMN IF NOT EXISTS hot_water_system text,
ADD COLUMN IF NOT EXISTS solar_panels boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS solar_hot_water boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS rainwater_tank boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS greywater_system boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS energy_rating text,
ADD COLUMN IF NOT EXISTS water_rating text,
ADD COLUMN IF NOT EXISTS nbers_rating text,
ADD COLUMN IF NOT EXISTS green_star_rating text,
ADD COLUMN IF NOT EXISTS rental_history jsonb,
ADD COLUMN IF NOT EXISTS previous_sales jsonb,
ADD COLUMN IF NOT EXISTS market_commentary text,
ADD COLUMN IF NOT EXISTS location_benefits text,
ADD COLUMN IF NOT EXISTS location_detriments text,
ADD COLUMN IF NOT EXISTS comparable_sales_analysis text,
ADD COLUMN IF NOT EXISTS adjustment_summary text,
ADD COLUMN IF NOT EXISTS valuer_comments text,
ADD COLUMN IF NOT EXISTS inspection_date date,
ADD COLUMN IF NOT EXISTS sale_type text,
ADD COLUMN IF NOT EXISTS sale_conditions text,
ADD COLUMN IF NOT EXISTS vendor_type text,
ADD COLUMN IF NOT EXISTS purchaser_type text,
ADD COLUMN IF NOT EXISTS marketing_period_days integer,
ADD COLUMN IF NOT EXISTS listing_price numeric,
ADD COLUMN IF NOT EXISTS reserve_price numeric,
ADD COLUMN IF NOT EXISTS auction_result text,
ADD COLUMN IF NOT EXISTS settlement_date date,
ADD COLUMN IF NOT EXISTS stamp_duty numeric,
ADD COLUMN IF NOT EXISTS legal_costs numeric,
ADD COLUMN IF NOT EXISTS agent_commission numeric,
ADD COLUMN IF NOT EXISTS marketing_costs numeric,
ADD COLUMN IF NOT EXISTS is_new_build boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_off_the_plan boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_deceased_estate boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_mortgagee_sale boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS is_related_party_sale boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS days_on_market integer,
ADD COLUMN IF NOT EXISTS price_per_sqm_building numeric,
ADD COLUMN IF NOT EXISTS price_per_sqm_land numeric,
ADD COLUMN IF NOT EXISTS gross_rental_yield numeric,
ADD COLUMN IF NOT EXISTS net_rental_yield numeric,
ADD COLUMN IF NOT EXISTS capital_growth_rate numeric,
ADD COLUMN IF NOT EXISTS comparable_rank integer,
ADD COLUMN IF NOT EXISTS reliability_score integer,
ADD COLUMN IF NOT EXISTS data_source_verified boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS last_verified_date date,
ADD COLUMN IF NOT EXISTS extraction_confidence numeric,
ADD COLUMN IF NOT EXISTS data_quality_score integer;