-- Add comprehensive fields to rental_evidence table
ALTER TABLE public.rental_evidence 
ADD COLUMN IF NOT EXISTS unit_number text,
ADD COLUMN IF NOT EXISTS street_number text,
ADD COLUMN IF NOT EXISTS street_name text,
ADD COLUMN IF NOT EXISTS street_type text,
ADD COLUMN IF NOT EXISTS suburb text,
ADD COLUMN IF NOT EXISTS state text,
ADD COLUMN IF NOT EXISTS postcode text,
ADD COLUMN IF NOT EXISTS lot_number text,
ADD COLUMN IF NOT EXISTS plan_number text,
ADD COLUMN IF NOT EXISTS plan_type text,
ADD COLUMN IF NOT EXISTS local_government_area text,
ADD COLUMN IF NOT EXISTS ward text,
ADD COLUMN IF NOT EXISTS parish text,
ADD COLUMN IF NOT EXISTS county text,
ADD COLUMN IF NOT EXISTS title_particulars text,
ADD COLUMN IF NOT EXISTS zoning text,
ADD COLUMN IF NOT EXISTS property_description text,
ADD COLUMN IF NOT EXISTS building_type text,
ADD COLUMN IF NOT EXISTS construction_type text,
ADD COLUMN IF NOT EXISTS roof_type text,
ADD COLUMN IF NOT EXISTS external_walls text,
ADD COLUMN IF NOT EXISTS year_built integer,
ADD COLUMN IF NOT EXISTS year_renovated integer,
ADD COLUMN IF NOT EXISTS condition_rating text,
ADD COLUMN IF NOT EXISTS quality_rating text,
ADD COLUMN IF NOT EXISTS view_rating text,
ADD COLUMN IF NOT EXISTS aspect text,
ADD COLUMN IF NOT EXISTS topography text,
ADD COLUMN IF NOT EXISTS soil_type text,
ADD COLUMN IF NOT EXISTS services text,
ADD COLUMN IF NOT EXISTS easements text,
ADD COLUMN IF NOT EXISTS encumbrances text,
ADD COLUMN IF NOT EXISTS heritage_listing boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS flooding_risk text,
ADD COLUMN IF NOT EXISTS bushfire_risk text,
ADD COLUMN IF NOT EXISTS coastal_erosion_risk text,
ADD COLUMN IF NOT EXISTS contamination_risk text,
ADD COLUMN IF NOT EXISTS is_strata boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS strata_scheme_number text,
ADD COLUMN IF NOT EXISTS strata_lot_number text,
ADD COLUMN IF NOT EXISTS strata_plan_number text,
ADD COLUMN IF NOT EXISTS strata_manager text,
ADD COLUMN IF NOT EXISTS strata_fees_quarterly numeric,
ADD COLUMN IF NOT EXISTS strata_fees_annual numeric,
ADD COLUMN IF NOT EXISTS sinking_fund_balance numeric,
ADD COLUMN IF NOT EXISTS administrative_fund_balance numeric,
ADD COLUMN IF NOT EXISTS special_levies numeric,
ADD COLUMN IF NOT EXISTS body_corporate_name text,
ADD COLUMN IF NOT EXISTS management_rights boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS letting_rights boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS common_property_description text,
ADD COLUMN IF NOT EXISTS exclusive_use_areas text,
ADD COLUMN IF NOT EXISTS parking_type text,
ADD COLUMN IF NOT EXISTS parking_spaces integer,
ADD COLUMN IF NOT EXISTS storage_areas text,
ADD COLUMN IF NOT EXISTS balcony_area numeric,
ADD COLUMN IF NOT EXISTS courtyard_area numeric,
ADD COLUMN IF NOT EXISTS garden_area numeric,
ADD COLUMN IF NOT EXISTS pool boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS spa boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS tennis_court boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS gym boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS security_features text,
ADD COLUMN IF NOT EXISTS lift_access boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS wheelchair_access boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS air_conditioning text,
ADD COLUMN IF NOT EXISTS heating text,
ADD COLUMN IF NOT EXISTS hot_water_system text,
ADD COLUMN IF NOT EXISTS solar_panels boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS solar_hot_water boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS rainwater_tank boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS greywater_system boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS energy_rating text,
ADD COLUMN IF NOT EXISTS water_rating text,
ADD COLUMN IF NOT EXISTS nbers_rating text,
ADD COLUMN IF NOT EXISTS green_star_rating text,
ADD COLUMN IF NOT EXISTS previous_rentals jsonb,
ADD COLUMN IF NOT EXISTS sales_history jsonb,
ADD COLUMN IF NOT EXISTS market_commentary text,
ADD COLUMN IF NOT EXISTS location_benefits text,
ADD COLUMN IF NOT EXISTS location_detriments text,
ADD COLUMN IF NOT EXISTS comparable_rentals_analysis text,
ADD COLUMN IF NOT EXISTS adjustment_summary text,
ADD COLUMN IF NOT EXISTS valuer_comments text,
ADD COLUMN IF NOT EXISTS inspection_date date,
ADD COLUMN IF NOT EXISTS lease_type text,
ADD COLUMN IF NOT EXISTS lease_conditions text,
ADD COLUMN IF NOT EXISTS tenant_type text,
ADD COLUMN IF NOT EXISTS landlord_type text,
ADD COLUMN IF NOT EXISTS marketing_period_days integer,
ADD COLUMN IF NOT EXISTS asking_rent numeric,
ADD COLUMN IF NOT EXISTS rent_review_date date,
ADD COLUMN IF NOT EXISTS rent_increase_percentage numeric,
ADD COLUMN IF NOT EXISTS bond_amount numeric,
ADD COLUMN IF NOT EXISTS pet_policy text,
ADD COLUMN IF NOT EXISTS furnished boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS utilities_included text,
ADD COLUMN IF NOT EXISTS internet_included boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS parking_included boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS storage_included boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS garden_maintenance boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS pool_maintenance boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS lease_start_date date,
ADD COLUMN IF NOT EXISTS lease_end_date date,
ADD COLUMN IF NOT EXISTS lease_renewal_options text,
ADD COLUMN IF NOT EXISTS break_clause text,
ADD COLUMN IF NOT EXISTS rental_guarantees text,
ADD COLUMN IF NOT EXISTS rental_incentives text,
ADD COLUMN IF NOT EXISTS vacancy_period_days integer,
ADD COLUMN IF NOT EXISTS rent_per_week numeric,
ADD COLUMN IF NOT EXISTS rent_per_month numeric,
ADD COLUMN IF NOT EXISTS rent_per_sqm_annual numeric,
ADD COLUMN IF NOT EXISTS comparable_rank integer,
ADD COLUMN IF NOT EXISTS reliability_score integer,
ADD COLUMN IF NOT EXISTS data_source_verified boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS last_verified_date date,
ADD COLUMN IF NOT EXISTS extraction_confidence numeric,
ADD COLUMN IF NOT EXISTS data_quality_score integer;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_sales_evidence_strata ON public.sales_evidence(is_strata);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_property_type_strata ON public.sales_evidence(property_type, is_strata);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_suburb_state ON public.sales_evidence(suburb, state);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_year_built ON public.sales_evidence(year_built);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_data_quality ON public.sales_evidence(data_quality_score);

CREATE INDEX IF NOT EXISTS idx_rental_evidence_strata ON public.rental_evidence(is_strata);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_property_type_strata ON public.rental_evidence(property_type, is_strata);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_suburb_state ON public.rental_evidence(suburb, state);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_year_built ON public.rental_evidence(year_built);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_data_quality ON public.rental_evidence(data_quality_score);