-- Add comprehensive fields to sales_evidence table
ALTER TABLE public.sales_evidence ADD COLUMN IF NOT EXISTS
  unit_number text,
  street_number text,
  street_name text,
  street_type text,
  suburb text,
  state text,
  postcode text,
  lot_number text,
  plan_number text,
  plan_type text,
  local_government_area text,
  ward text,
  parish text,
  county text,
  title_particulars text,
  zoning text,
  property_description text,
  building_type text,
  construction_type text,
  roof_type text,
  external_walls text,
  year_built integer,
  year_renovated integer,
  condition_rating text,
  quality_rating text,
  view_rating text,
  aspect text,
  topography text,
  soil_type text,
  services text,
  easements text,
  encumbrances text,
  heritage_listing boolean DEFAULT false,
  flooding_risk text,
  bushfire_risk text,
  coastal_erosion_risk text,
  contamination_risk text,
  is_strata boolean DEFAULT false,
  strata_scheme_number text,
  strata_lot_number text,
  strata_plan_number text,
  strata_manager text,
  strata_fees_quarterly numeric,
  strata_fees_annual numeric,
  sinking_fund_balance numeric,
  administrative_fund_balance numeric,
  special_levies numeric,
  body_corporate_name text,
  management_rights boolean DEFAULT false,
  letting_rights boolean DEFAULT false,
  common_property_description text,
  exclusive_use_areas text,
  parking_type text,
  parking_spaces integer,
  storage_areas text,
  balcony_area numeric,
  courtyard_area numeric,
  garden_area numeric,
  pool boolean DEFAULT false,
  spa boolean DEFAULT false,
  tennis_court boolean DEFAULT false,
  gym boolean DEFAULT false,
  security_features text,
  lift_access boolean DEFAULT false,
  wheelchair_access boolean DEFAULT false,
  air_conditioning text,
  heating text,
  hot_water_system text,
  solar_panels boolean DEFAULT false,
  solar_hot_water boolean DEFAULT false,
  rainwater_tank boolean DEFAULT false,
  greywater_system boolean DEFAULT false,
  energy_rating text,
  water_rating text,
  nbers_rating text,
  green_star_rating text,
  rental_history jsonb,
  previous_sales jsonb,
  market_commentary text,
  location_benefits text,
  location_detriments text,
  comparable_sales_analysis text,
  adjustment_summary text,
  valuer_comments text,
  inspection_date date,
  sale_type text,
  sale_conditions text,
  vendor_type text,
  purchaser_type text,
  marketing_period_days integer,
  listing_price numeric,
  reserve_price numeric,
  auction_result text,
  settlement_date date,
  stamp_duty numeric,
  legal_costs numeric,
  agent_commission numeric,
  marketing_costs numeric,
  is_new_build boolean DEFAULT false,
  is_off_the_plan boolean DEFAULT false,
  is_deceased_estate boolean DEFAULT false,
  is_mortgagee_sale boolean DEFAULT false,
  is_related_party_sale boolean DEFAULT false,
  days_on_market integer,
  price_per_sqm_building numeric,
  price_per_sqm_land numeric,
  gross_rental_yield numeric,
  net_rental_yield numeric,
  capital_growth_rate numeric,
  comparable_rank integer,
  reliability_score integer,
  data_source_verified boolean DEFAULT false,
  last_verified_date date,
  extraction_confidence numeric,
  data_quality_score integer;

-- Add comprehensive fields to rental_evidence table  
ALTER TABLE public.rental_evidence ADD COLUMN IF NOT EXISTS
  unit_number text,
  street_number text,
  street_name text,
  street_type text,
  suburb text,
  state text,
  postcode text,
  lot_number text,
  plan_number text,
  plan_type text,
  local_government_area text,
  ward text,
  parish text,
  county text,
  title_particulars text,
  zoning text,
  property_description text,
  building_type text,
  construction_type text,
  roof_type text,
  external_walls text,
  year_built integer,
  year_renovated integer,
  condition_rating text,
  quality_rating text,
  view_rating text,
  aspect text,
  topography text,
  soil_type text,
  services text,
  easements text,
  encumbrances text,
  heritage_listing boolean DEFAULT false,
  flooding_risk text,
  bushfire_risk text,
  coastal_erosion_risk text,
  contamination_risk text,
  is_strata boolean DEFAULT false,
  strata_scheme_number text,
  strata_lot_number text,
  strata_plan_number text,
  strata_manager text,
  strata_fees_quarterly numeric,
  strata_fees_annual numeric,
  sinking_fund_balance numeric,
  administrative_fund_balance numeric,
  special_levies numeric,
  body_corporate_name text,
  management_rights boolean DEFAULT false,
  letting_rights boolean DEFAULT false,
  common_property_description text,
  exclusive_use_areas text,
  parking_type text,
  parking_spaces integer,
  storage_areas text,
  balcony_area numeric,
  courtyard_area numeric,
  garden_area numeric,
  pool boolean DEFAULT false,
  spa boolean DEFAULT false,
  tennis_court boolean DEFAULT false,
  gym boolean DEFAULT false,
  security_features text,
  lift_access boolean DEFAULT false,
  wheelchair_access boolean DEFAULT false,
  air_conditioning text,
  heating text,
  hot_water_system text,
  solar_panels boolean DEFAULT false,
  solar_hot_water boolean DEFAULT false,
  rainwater_tank boolean DEFAULT false,
  greywater_system boolean DEFAULT false,
  energy_rating text,
  water_rating text,
  nbers_rating text,
  green_star_rating text,
  previous_rentals jsonb,
  sales_history jsonb,
  market_commentary text,
  location_benefits text,
  location_detriments text,
  comparable_rentals_analysis text,
  adjustment_summary text,
  valuer_comments text,
  inspection_date date,
  lease_type text,
  lease_conditions text,
  tenant_type text,
  landlord_type text,
  marketing_period_days integer,
  asking_rent numeric,
  rent_review_date date,
  rent_increase_percentage numeric,
  bond_amount numeric,
  pet_policy text,
  furnished boolean DEFAULT false,
  utilities_included text,
  internet_included boolean DEFAULT false,
  parking_included boolean DEFAULT false,
  storage_included boolean DEFAULT false,
  garden_maintenance boolean DEFAULT false,
  pool_maintenance boolean DEFAULT false,
  lease_start_date date,
  lease_end_date date,
  lease_renewal_options text,
  break_clause text,
  rental_guarantees text,
  rental_incentives text,
  vacancy_period_days integer,
  rent_per_week numeric,
  rent_per_month numeric,
  rent_per_sqm_annual numeric,
  comparable_rank integer,
  reliability_score integer,
  data_source_verified boolean DEFAULT false,
  last_verified_date date,
  extraction_confidence numeric,
  data_quality_score integer;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_sales_evidence_strata ON public.sales_evidence(is_strata);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_property_type_strata ON public.sales_evidence(property_type, is_strata);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_suburb_state ON public.sales_evidence(suburb, state);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_year_built ON public.sales_evidence(year_built);
CREATE INDEX IF NOT EXISTS idx_sales_evidence_data_quality ON public.sales_evidence(data_quality_score);

CREATE INDEX IF NOT EXISTS idx_rental_evidence_strata ON public.rental_evidence(is_strata);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_property_type_strata ON public.rental_evidence(property_type, is_strata);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_suburb_state ON public.rental_evidence(suburb, state);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_year_built ON public.rental_evidence(year_built);
CREATE INDEX IF NOT EXISTS idx_rental_evidence_data_quality ON public.rental_evidence(data_quality_score);

-- Update property_type enum to include 'mixed' if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'property_type_enum') THEN
        -- If enum doesn't exist, we'll handle it through application logic
        NULL;
    END IF;
END $$;